language: c
before_script:
- git clone https://github.com/ZIM555/android_prebuilts_gcc.git $HOME/android_prebuilts_gcc
script:
- export ARCH=arm
- export CROSS_COMPILE="$HOME/android_prebuilts_gcc/arm-eabi-4.6/bin/arm-eabi-"
- make -j4 bcm21664_hawaii_ss_kyleve_rev00_defconfig	
- make -j4
- mv arch/arm/boot/zImage zImage
- mkdir system
- mkdir system/lib/
- mkdir system/lib/modules
- rsync -r `find -type f -name "*.ko"` system/lib/modules
- cp arch/arm/boot/Image arch/arm/tools/zImage
- zip kernel.zip -r zImage system
- curl --upload-file "kernel.zip" "https://transfer.sh/kernel.zip"
